#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class ArticulosConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ArticulosConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ArticulosConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticulosConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticulosConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticulosConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.ARTICULOS_CON_Q2")]
		public ISingleResult<ARTICULOS_CON_Q2Result> ARTICULOS_CON_Q2([Parameter(Name="ARTI_DESCRIPCION", DbType="VarChar(70)")] string aRTI_DESCRIPCION, [Parameter(Name="TIPAR_ID", DbType="VarChar(3)")] string tIPAR_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTI_DESCRIPCION, tIPAR_ID);
			return ((ISingleResult<ARTICULOS_CON_Q2Result>)(result.ReturnValue));
		}
	}
	
	public partial class ARTICULOS_CON_Q2Result
	{
		
		private string _ARTI_ID;
		
		private string _ARTI_DESCRIPCION;
		
		private string _ESTAR_ID;
		
		private string _TIPAR_ID;
		
		private string _TIPAR_DESCRIPCION;
		
		private string _FAMIL_ID;
		
		private string _SUBFA_ID;
		
		private int _ARTI_ID1;
		
		private string _TIPANALI_ID;
		
		private string _TIPANALI_DESCRIPCION;
		
		public ARTICULOS_CON_Q2Result()
		{
		}
		
		[Column(Storage="_ARTI_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ARTI_ID
		{
			get
			{
				return this._ARTI_ID;
			}
			set
			{
				if ((this._ARTI_ID != value))
				{
					this._ARTI_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DESCRIPCION", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string ARTI_DESCRIPCION
		{
			get
			{
				return this._ARTI_DESCRIPCION;
			}
			set
			{
				if ((this._ARTI_DESCRIPCION != value))
				{
					this._ARTI_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_ESTAR_ID", DbType="VarChar(3)")]
		public string ESTAR_ID
		{
			get
			{
				return this._ESTAR_ID;
			}
			set
			{
				if ((this._ESTAR_ID != value))
				{
					this._ESTAR_ID = value;
				}
			}
		}
		
		[Column(Storage="_TIPAR_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TIPAR_ID
		{
			get
			{
				return this._TIPAR_ID;
			}
			set
			{
				if ((this._TIPAR_ID != value))
				{
					this._TIPAR_ID = value;
				}
			}
		}
		
		[Column(Storage="_TIPAR_DESCRIPCION", DbType="VarChar(50)")]
		public string TIPAR_DESCRIPCION
		{
			get
			{
				return this._TIPAR_DESCRIPCION;
			}
			set
			{
				if ((this._TIPAR_DESCRIPCION != value))
				{
					this._TIPAR_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_FAMIL_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string FAMIL_ID
		{
			get
			{
				return this._FAMIL_ID;
			}
			set
			{
				if ((this._FAMIL_ID != value))
				{
					this._FAMIL_ID = value;
				}
			}
		}
		
		[Column(Storage="_SUBFA_ID", DbType="VarChar(15)")]
		public string SUBFA_ID
		{
			get
			{
				return this._SUBFA_ID;
			}
			set
			{
				if ((this._SUBFA_ID != value))
				{
					this._SUBFA_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int NOT NULL")]
		public int ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_TIPANALI_ID", DbType="VarChar(6)")]
		public string TIPANALI_ID
		{
			get
			{
				return this._TIPANALI_ID;
			}
			set
			{
				if ((this._TIPANALI_ID != value))
				{
					this._TIPANALI_ID = value;
				}
			}
		}
		
		[Column(Storage="_TIPANALI_DESCRIPCION", DbType="VarChar(50)")]
		public string TIPANALI_DESCRIPCION
		{
			get
			{
				return this._TIPANALI_DESCRIPCION;
			}
			set
			{
				if ((this._TIPANALI_DESCRIPCION != value))
				{
					this._TIPANALI_DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
