#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class ClientesConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ClientesConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClientesConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClientesConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClientesConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClientesConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.CLIENTES_CON1_Q2")]
		public ISingleResult<CLIENTES_CON1_Q2Result> CLIENTES_CON1_Q2([Parameter(Name="TIPO", DbType="Int")] System.Nullable<int> tIPO, [Parameter(Name="USU_ID", DbType="VarChar(15)")] string uSU_ID, [Parameter(Name="CLIE_DESCRIPCION", DbType="VarChar(50)")] string cLIE_DESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, uSU_ID, cLIE_DESCRIPCION);
			return ((ISingleResult<CLIENTES_CON1_Q2Result>)(result.ReturnValue));
		}
	}
	
	public partial class CLIENTES_CON1_Q2Result
	{
		
		private int _CLIE_ID;
		
		private string _CLIE_DESCRIPCION;
		
		public CLIENTES_CON1_Q2Result()
		{
		}
		
		[Column(Storage="_CLIE_ID", DbType="Int NOT NULL")]
		public int CLIE_ID
		{
			get
			{
				return this._CLIE_ID;
			}
			set
			{
				if ((this._CLIE_ID != value))
				{
					this._CLIE_ID = value;
				}
			}
		}
		
		[Column(Storage="_CLIE_DESCRIPCION", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CLIE_DESCRIPCION
		{
			get
			{
				return this._CLIE_DESCRIPCION;
			}
			set
			{
				if ((this._CLIE_DESCRIPCION != value))
				{
					this._CLIE_DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
