#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class EstadosDocumentoConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EstadosDocumentoConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EstadosDocumentoConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EstadosDocumentoConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EstadosDocumentoConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EstadosDocumentoConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.DOCUMENTOS_ESTADOS_CON")]
		public ISingleResult<DOCUMENTOS_ESTADOS_CONResult> DOCUMENTOS_ESTADOS_CON([Parameter(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, [Parameter(Name="USUARIO", DbType="VarChar(15)")] string uSUARIO, [Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, uSUARIO, dOCU_ID);
			return ((ISingleResult<DOCUMENTOS_ESTADOS_CONResult>)(result.ReturnValue));
		}
	}
	
	public partial class DOCUMENTOS_ESTADOS_CONResult
	{
		
		private string _DOCU_ID;
		
		private string _ESTDOC_ID;
		
		private string _ESTDOC_DESCRIPCION;
		
		public DOCUMENTOS_ESTADOS_CONResult()
		{
		}
		
		[Column(Storage="_DOCU_ID", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DOCU_ID
		{
			get
			{
				return this._DOCU_ID;
			}
			set
			{
				if ((this._DOCU_ID != value))
				{
					this._DOCU_ID = value;
				}
			}
		}
		
		[Column(Storage="_ESTDOC_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string ESTDOC_ID
		{
			get
			{
				return this._ESTDOC_ID;
			}
			set
			{
				if ((this._ESTDOC_ID != value))
				{
					this._ESTDOC_ID = value;
				}
			}
		}
		
		[Column(Storage="_ESTDOC_DESCRIPCION", DbType="VarChar(50)")]
		public string ESTDOC_DESCRIPCION
		{
			get
			{
				return this._ESTDOC_DESCRIPCION;
			}
			set
			{
				if ((this._ESTDOC_DESCRIPCION != value))
				{
					this._ESTDOC_DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
