#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class FormasPagoConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FormasPagoConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FormasPagoConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FormasPagoConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FormasPagoConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FormasPagoConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.FORMAS_PAGO_Q2_CON")]
		public ISingleResult<FORMAS_PAGO_Q2_CONResult> FORMAS_PAGO_Q2_CON()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<FORMAS_PAGO_Q2_CONResult>)(result.ReturnValue));
		}
	}
	
	public partial class FORMAS_PAGO_Q2_CONResult
	{
		
		private int _FPAGO_ID;
		
		private string _FPAGO_DESCRIPCION;
		
		public FORMAS_PAGO_Q2_CONResult()
		{
		}
		
		[Column(Storage="_FPAGO_ID", DbType="Int NOT NULL")]
		public int FPAGO_ID
		{
			get
			{
				return this._FPAGO_ID;
			}
			set
			{
				if ((this._FPAGO_ID != value))
				{
					this._FPAGO_ID = value;
				}
			}
		}
		
		[Column(Storage="_FPAGO_DESCRIPCION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FPAGO_DESCRIPCION
		{
			get
			{
				return this._FPAGO_DESCRIPCION;
			}
			set
			{
				if ((this._FPAGO_DESCRIPCION != value))
				{
					this._FPAGO_DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
