#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class GruposCondicionesConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public GruposCondicionesConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GruposCondicionesConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GruposCondicionesConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GruposCondicionesConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GruposCondicionesConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.GRUPOS_DESCUENTOS_CON")]
		public ISingleResult<GRUPOS_DESCUENTOS_CONResult> GRUPOS_DESCUENTOS_CON([Parameter(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, [Parameter(Name="USUARIO", DbType="VarChar(15)")] string uSUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, uSUARIO);
			return ((ISingleResult<GRUPOS_DESCUENTOS_CONResult>)(result.ReturnValue));
		}
	}
	
	public partial class GRUPOS_DESCUENTOS_CONResult
	{
		
		private int _GRDE_ID;
		
		private string _GRDE_DESCRIPCION;
		
		public GRUPOS_DESCUENTOS_CONResult()
		{
		}
		
		[Column(Storage="_GRDE_ID", DbType="Int NOT NULL")]
		public int GRDE_ID
		{
			get
			{
				return this._GRDE_ID;
			}
			set
			{
				if ((this._GRDE_ID != value))
				{
					this._GRDE_ID = value;
				}
			}
		}
		
		[Column(Storage="_GRDE_DESCRIPCION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GRDE_DESCRIPCION
		{
			get
			{
				return this._GRDE_DESCRIPCION;
			}
			set
			{
				if ((this._GRDE_DESCRIPCION != value))
				{
					this._GRDE_DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
