<?xml version="1.0" encoding="utf-8"?>
<Database Name="local" Class="MediadoresConsultaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=INFORMATICA02\SQLSRV2008;Initial Catalog=local;Integrated Security=True" SettingsObjectName="DocumentosVentas.Properties.Settings" SettingsPropertyName="localConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.CLIENTES_MEDIADOR_SEL" Method="CLIENTES_MEDIADOR_SEL">
    <Parameter Name="TIPO" Parameter="tIPO" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="USUARIO" Parameter="uSUARIO" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="CLIE_ID" Parameter="cLIE_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="CLIENTES_MEDIADOR_SELResult">
      <Column Name="CLIE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="REPRE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MEDIA_SIEMPRE" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="APLICA_PRECIO_MEDIADOR" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="COMUNICA" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="REPRE_DESCRIPCION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>