<?xml version="1.0" encoding="utf-8"?>
<Database Name="local" Class="MonedasConsultaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=INFORMATICA02\SQLSRV2008;Initial Catalog=local;Integrated Security=True" SettingsObjectName="DocumentosVentas.Properties.Settings" SettingsPropertyName="localConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.MONEDAS_Q2_CON" Method="MONEDAS_Q2_CON">
    <ElementType Name="MONEDAS_Q2_CONResult">
      <Column Name="MONEDA_ID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="MONEDA_DESCRIPCION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>