#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class MonedasConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MonedasConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MonedasConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonedasConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonedasConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonedasConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.MONEDAS_Q2_CON")]
		public ISingleResult<MONEDAS_Q2_CONResult> MONEDAS_Q2_CON()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MONEDAS_Q2_CONResult>)(result.ReturnValue));
		}
	}
	
	public partial class MONEDAS_Q2_CONResult
	{
		
		private string _MONEDA_ID;
		
		private string _MONEDA_DESCRIPCION;
		
		public MONEDAS_Q2_CONResult()
		{
		}
		
		[Column(Storage="_MONEDA_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string MONEDA_ID
		{
			get
			{
				return this._MONEDA_ID;
			}
			set
			{
				if ((this._MONEDA_ID != value))
				{
					this._MONEDA_ID = value;
				}
			}
		}
		
		[Column(Storage="_MONEDA_DESCRIPCION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MONEDA_DESCRIPCION
		{
			get
			{
				return this._MONEDA_DESCRIPCION;
			}
			set
			{
				if ((this._MONEDA_DESCRIPCION != value))
				{
					this._MONEDA_DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
