<?xml version="1.0" encoding="utf-8"?>
<Database Name="local" Class="PaisesConsultaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=INFORMATICA02\SQLSRV2008;Initial Catalog=local;Integrated Security=True" SettingsObjectName="DocumentosVentas.Properties.Settings" SettingsPropertyName="localConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.PAISES_Q2_CON" Method="PAISES_Q2_CON">
    <ElementType Name="PAISES_Q2_CONResult">
      <Column Name="PAIS_ID" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="PAIS_DESCRIPCION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>