#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class PaisesConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PaisesConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PaisesConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaisesConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaisesConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaisesConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.PAISES_Q2_CON")]
		public ISingleResult<PAISES_Q2_CONResult> PAISES_Q2_CON()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PAISES_Q2_CONResult>)(result.ReturnValue));
		}
	}
	
	public partial class PAISES_Q2_CONResult
	{
		
		private string _PAIS_ID;
		
		private string _PAIS_DESCRIPCION;
		
		public PAISES_Q2_CONResult()
		{
		}
		
		[Column(Storage="_PAIS_ID", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string PAIS_ID
		{
			get
			{
				return this._PAIS_ID;
			}
			set
			{
				if ((this._PAIS_ID != value))
				{
					this._PAIS_ID = value;
				}
			}
		}
		
		[Column(Storage="_PAIS_DESCRIPCION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PAIS_DESCRIPCION
		{
			get
			{
				return this._PAIS_DESCRIPCION;
			}
			set
			{
				if ((this._PAIS_DESCRIPCION != value))
				{
					this._PAIS_DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
