#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class PedidovDetalleDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PedidovDetalleDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PedidovDetalleDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PedidovDetalleDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PedidovDetalleDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PedidovDetalleDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.MODELOS_DETALLE_Q2")]
		public ISingleResult<MODELOS_DETALLE_Q2Result> MODELOS_DETALLE_Q2([Parameter(Name="TIPANA_ID", DbType="NVarChar(12)")] string tIPANA_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPANA_ID);
			return ((ISingleResult<MODELOS_DETALLE_Q2Result>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.TIPANA_MATRIZ_CON_Q2")]
		public ISingleResult<TIPANA_MATRIZ_CON_Q2Result> TIPANA_MATRIZ_CON_Q2([Parameter(Name="ARTI_ID", DbType="VarChar(15)")] string aRTI_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTI_ID);
			return ((ISingleResult<TIPANA_MATRIZ_CON_Q2Result>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.DETERMINACIONES_DETALLE_Q2")]
		public ISingleResult<DETERMINACIONES_DETALLE_Q2Result> DETERMINACIONES_DETALLE_Q2([Parameter(Name="TIPANA_ID", DbType="NVarChar(12)")] string tIPANA_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPANA_ID);
			return ((ISingleResult<DETERMINACIONES_DETALLE_Q2Result>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_DETERMINACIONES_BY_TIPO_ANALISIS")]
		public ISingleResult<Q2_GET_DETERMINACIONES_BY_TIPO_ANALISISResult> Q2_GET_DETERMINACIONES_BY_TIPO_ANALISIS([Parameter(Name="TIPANA_ID", DbType="VarChar(6)")] string tIPANA_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPANA_ID);
			return ((ISingleResult<Q2_GET_DETERMINACIONES_BY_TIPO_ANALISISResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_MODELOS_BY_TIPO_ANALISIS")]
		public ISingleResult<Q2_GET_MODELOS_BY_TIPO_ANALISISResult> Q2_GET_MODELOS_BY_TIPO_ANALISIS([Parameter(Name="TIPANA_ID", DbType="VarChar(6)")] string tIPANA_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPANA_ID);
			return ((ISingleResult<Q2_GET_MODELOS_BY_TIPO_ANALISISResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_ARTICULOS_CARGO_BY_TIPO_ANALISIS")]
		public ISingleResult<Q2_GET_ARTICULOS_CARGO_BY_TIPO_ANALISISResult> Q2_GET_ARTICULOS_CARGO_BY_TIPO_ANALISIS([Parameter(Name="TIPANA_ID", DbType="VarChar(6)")] string tIPANA_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPANA_ID);
			return ((ISingleResult<Q2_GET_ARTICULOS_CARGO_BY_TIPO_ANALISISResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_ARTICULOS_CARGO_SERVICIOS_E_INFORMES")]
		public ISingleResult<Q2_GET_ARTICULOS_CARGO_SERVICIOS_E_INFORMESResult> Q2_GET_ARTICULOS_CARGO_SERVICIOS_E_INFORMES()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Q2_GET_ARTICULOS_CARGO_SERVICIOS_E_INFORMESResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_BLOQUES_GRUPO_BY_CLIENTE")]
		public ISingleResult<Q2_GET_BLOQUES_GRUPO_BY_CLIENTEResult> Q2_GET_BLOQUES_GRUPO_BY_CLIENTE([Parameter(Name="CLIE_ID", DbType="Int")] System.Nullable<int> cLIE_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cLIE_ID);
			return ((ISingleResult<Q2_GET_BLOQUES_GRUPO_BY_CLIENTEResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_DETALLE_BY_BLOQUE")]
		public ISingleResult<Q2_GET_DETALLE_BY_BLOQUEResult> Q2_GET_DETALLE_BY_BLOQUE([Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, [Parameter(Name="PRESUV_ID", DbType="VarChar(15)")] string pRESUV_ID, [Parameter(Name="BLOQUE_ID", DbType="Int")] System.Nullable<int> bLOQUE_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCU_ID, pRESUV_ID, bLOQUE_ID);
			return ((ISingleResult<Q2_GET_DETALLE_BY_BLOQUEResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_ASOCIADOS")]
		public ISingleResult<Q2_GET_ASOCIADOSResult> Q2_GET_ASOCIADOS([Parameter(Name="ARTI_ID1", DbType="Int")] System.Nullable<int> aRTI_ID1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTI_ID1);
			return ((ISingleResult<Q2_GET_ASOCIADOSResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_PEDIDOSV_LI_INS")]
		public int Q2_PEDIDOSV_LI_INS(
					[Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, 
					[Parameter(Name="PEDID_ID", DbType="VarChar(15)")] string pEDID_ID, 
					[Parameter(Name="PEDIDL_LINEA", DbType="Int")] System.Nullable<int> pEDIDL_LINEA, 
					[Parameter(Name="PEDIDL_SUBLINEA", DbType="Int")] System.Nullable<int> pEDIDL_SUBLINEA, 
					[Parameter(Name="LIDO_ID", DbType="VarChar(6)")] string lIDO_ID, 
					[Parameter(Name="PEDIDL_DESCRIPCION", DbType="VarChar(255)")] string pEDIDL_DESCRIPCION, 
					[Parameter(Name="PEDIDL_CANTIDAD", DbType="Decimal")] System.Nullable<decimal> pEDIDL_CANTIDAD, 
					[Parameter(Name="PEDIDL_PRECIO", DbType="Decimal")] System.Nullable<decimal> pEDIDL_PRECIO, 
					[Parameter(Name="GRDE_ID", DbType="Int")] System.Nullable<int> gRDE_ID, 
					[Parameter(Name="ESTDOC_ID", DbType="VarChar(3)")] string eSTDOC_ID, 
					[Parameter(Name="UNID_ID", DbType="VarChar(3)")] string uNID_ID, 
					[Parameter(Name="DOCU_ID_ORIGEN", DbType="VarChar(6)")] string dOCU_ID_ORIGEN, 
					[Parameter(Name="DOCU_NUMERO_ORIGEN", DbType="VarChar(15)")] string dOCU_NUMERO_ORIGEN, 
					[Parameter(Name="DOCU_LINEA_ORIGEN", DbType="Int")] System.Nullable<int> dOCU_LINEA_ORIGEN, 
					[Parameter(Name="DOCU_SUBLINEA_ORIGEN", DbType="Int")] System.Nullable<int> dOCU_SUBLINEA_ORIGEN, 
					[Parameter(Name="PEDIDL_FLUJOC", DbType="VarChar(1)")] string pEDIDL_FLUJOC, 
					[Parameter(Name="PEDIDL_FLUJOL", DbType="VarChar(1)")] string pEDIDL_FLUJOL, 
					[Parameter(Name="COMP_ID", DbType="Int")] System.Nullable<int> cOMP_ID, 
					[Parameter(Name="ARTI_ID1", DbType="Int")] System.Nullable<int> aRTI_ID1, 
					[Parameter(Name="PEDIDL_FECHAD_APLIC", DbType="VarChar(10)")] string pEDIDL_FECHAD_APLIC, 
					[Parameter(Name="PEDIDL_FECHAH_APLIC", DbType="VarChar(10)")] string pEDIDL_FECHAH_APLIC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCU_ID, pEDID_ID, pEDIDL_LINEA, pEDIDL_SUBLINEA, lIDO_ID, pEDIDL_DESCRIPCION, pEDIDL_CANTIDAD, pEDIDL_PRECIO, gRDE_ID, eSTDOC_ID, uNID_ID, dOCU_ID_ORIGEN, dOCU_NUMERO_ORIGEN, dOCU_LINEA_ORIGEN, dOCU_SUBLINEA_ORIGEN, pEDIDL_FLUJOC, pEDIDL_FLUJOL, cOMP_ID, aRTI_ID1, pEDIDL_FECHAD_APLIC, pEDIDL_FECHAH_APLIC);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_ELIMINAR_DETALLE_FONDO")]
		public int Q2_ELIMINAR_DETALLE_FONDO([Parameter(Name="DOCU_ACTA_ID", DbType="VarChar(6)")] string dOCU_ACTA_ID, [Parameter(Name="PEDID_ID", DbType="VarChar(15)")] string pEDID_ID, [Parameter(Name="PEDIDL_LINEA", DbType="Int")] System.Nullable<int> pEDIDL_LINEA, [Parameter(Name="PEDIDL_SUBLINEA", DbType="Int")] System.Nullable<int> pEDIDL_SUBLINEA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCU_ACTA_ID, pEDID_ID, pEDIDL_LINEA, pEDIDL_SUBLINEA);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_ELIMINAR_DETALLE")]
		public int Q2_ELIMINAR_DETALLE([Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, [Parameter(Name="PEDID_ID", DbType="VarChar(15)")] string pEDID_ID, [Parameter(Name="PEDIDL_LINEA", DbType="Int")] System.Nullable<int> pEDIDL_LINEA, [Parameter(Name="PEDIDL_SUBLINEA", DbType="Int")] System.Nullable<int> pEDIDL_SUBLINEA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCU_ID, pEDID_ID, pEDIDL_LINEA, pEDIDL_SUBLINEA);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_PEDIDOSV_LI_UPD")]
		public int Q2_PEDIDOSV_LI_UPD(
					[Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, 
					[Parameter(Name="PEDID_ID", DbType="VarChar(15)")] string pEDID_ID, 
					[Parameter(Name="PEDIDL_LINEA", DbType="Int")] System.Nullable<int> pEDIDL_LINEA, 
					[Parameter(Name="PEDIDL_SUBLINEA", DbType="Int")] System.Nullable<int> pEDIDL_SUBLINEA, 
					[Parameter(Name="LIDO_ID", DbType="VarChar(6)")] string lIDO_ID, 
					[Parameter(Name="PEDIDL_DESCRIPCION", DbType="VarChar(255)")] string pEDIDL_DESCRIPCION, 
					[Parameter(Name="PEDIDL_CANTIDAD", DbType="Decimal")] System.Nullable<decimal> pEDIDL_CANTIDAD, 
					[Parameter(Name="PEDIDL_PRECIO", DbType="Decimal")] System.Nullable<decimal> pEDIDL_PRECIO, 
					[Parameter(Name="GRDE_ID", DbType="Int")] System.Nullable<int> gRDE_ID, 
					[Parameter(Name="ESTDOC_ID", DbType="VarChar(3)")] string eSTDOC_ID, 
					[Parameter(Name="UNID_ID", DbType="VarChar(3)")] string uNID_ID, 
					[Parameter(Name="DOCU_ID_ORIGEN", DbType="VarChar(6)")] string dOCU_ID_ORIGEN, 
					[Parameter(Name="DOCU_NUMERO_ORIGEN", DbType="VarChar(15)")] string dOCU_NUMERO_ORIGEN, 
					[Parameter(Name="DOCU_LINEA_ORIGEN", DbType="Int")] System.Nullable<int> dOCU_LINEA_ORIGEN, 
					[Parameter(Name="DOCU_SUBLINEA_ORIGEN", DbType="Int")] System.Nullable<int> dOCU_SUBLINEA_ORIGEN, 
					[Parameter(Name="PEDIDL_FLUJOC", DbType="VarChar(1)")] string pEDIDL_FLUJOC, 
					[Parameter(Name="PEDIDL_FLUJOL", DbType="VarChar(1)")] string pEDIDL_FLUJOL, 
					[Parameter(Name="COMP_ID", DbType="Int")] System.Nullable<int> cOMP_ID, 
					[Parameter(Name="ARTI_ID1", DbType="Int")] System.Nullable<int> aRTI_ID1, 
					[Parameter(Name="PEDIDL_FECHAD_APLIC", DbType="VarChar(10)")] string pEDIDL_FECHAD_APLIC, 
					[Parameter(Name="PEDIDL_FECHAH_APLIC", DbType="VarChar(10)")] string pEDIDL_FECHAH_APLIC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCU_ID, pEDID_ID, pEDIDL_LINEA, pEDIDL_SUBLINEA, lIDO_ID, pEDIDL_DESCRIPCION, pEDIDL_CANTIDAD, pEDIDL_PRECIO, gRDE_ID, eSTDOC_ID, uNID_ID, dOCU_ID_ORIGEN, dOCU_NUMERO_ORIGEN, dOCU_LINEA_ORIGEN, dOCU_SUBLINEA_ORIGEN, pEDIDL_FLUJOC, pEDIDL_FLUJOL, cOMP_ID, aRTI_ID1, pEDIDL_FECHAD_APLIC, pEDIDL_FECHAH_APLIC);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_PEDIDO_ACTUALIZAR_ESTADO")]
		public int Q2_PEDIDO_ACTUALIZAR_ESTADO([Parameter(Name="ESTDOC_ID", DbType="VarChar(3)")] string eSTDOC_ID, [Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, [Parameter(Name="PEDID_ID", DbType="VarChar(15)")] string pEDID_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eSTDOC_ID, dOCU_ID, pEDID_ID);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.DOCUMENTO_ESTADO_INS")]
		public int DOCUMENTO_ESTADO_INS([Parameter(Name="USUARIO", DbType="VarChar(15)")] string uSUARIO, [Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, [Parameter(Name="NUMERO", DbType="VarChar(15)")] string nUMERO, [Parameter(Name="ESTDOC_ID", DbType="VarChar(3)")] string eSTDOC_ID, [Parameter(Name="EST_FECHA", DbType="VarChar(10)")] string eST_FECHA, [Parameter(Name="ESTADO_REGISTRO", DbType="VarChar(1)")] string eSTADO_REGISTRO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, dOCU_ID, nUMERO, eSTDOC_ID, eST_FECHA, eSTADO_REGISTRO);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_DETALLE_BY_PEDIDO2")]
		public ISingleResult<Q2_GET_DETALLE_BY_PEDIDO2Result> Q2_GET_DETALLE_BY_PEDIDO2([Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, [Parameter(Name="PEDID_ID", DbType="VarChar(15)")] string pEDID_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCU_ID, pEDID_ID);
			return ((ISingleResult<Q2_GET_DETALLE_BY_PEDIDO2Result>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_GET_COMP_IVA_CLIENTE")]
		public ISingleResult<Q2_GET_COMP_IVA_CLIENTEResult> Q2_GET_COMP_IVA_CLIENTE([Parameter(Name="CLIE_ID", DbType="Int")] System.Nullable<int> cLIE_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cLIE_ID);
			return ((ISingleResult<Q2_GET_COMP_IVA_CLIENTEResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.CLIENTES_COND_PRECIO2")]
		public ISingleResult<CLIENTES_COND_PRECIO2Result> CLIENTES_COND_PRECIO2([Parameter(Name="TIPO", DbType="Int")] System.Nullable<int> tIPO, [Parameter(Name="USUARIO", DbType="VarChar(15)")] string uSUARIO, [Parameter(Name="INTER_ID", DbType="Int")] System.Nullable<int> iNTER_ID, [Parameter(Name="FECHA", DbType="VarChar(10)")] string fECHA, [Parameter(Name="ARTI_ID1", DbType="Int")] System.Nullable<int> aRTI_ID1, [Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, uSUARIO, iNTER_ID, fECHA, aRTI_ID1, dOCU_ID);
			return ((ISingleResult<CLIENTES_COND_PRECIO2Result>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.Q2_PEDIDOSV_LI_SEL")]
		public ISingleResult<Q2_PEDIDOSV_LI_SELResult> Q2_PEDIDOSV_LI_SEL([Parameter(Name="PEDID_ID", DbType="VarChar(15)")] string pEDID_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pEDID_ID);
			return ((ISingleResult<Q2_PEDIDOSV_LI_SELResult>)(result.ReturnValue));
		}
	}
	
	public partial class MODELOS_DETALLE_Q2Result
	{
		
		private string _ARTI_ID;
		
		private string _ARTI_DESCRIPCION;
		
		private int _ARTI_ID1;
		
		private System.Nullable<bool> _ES_HIBRIDO;
		
		private string _ARTI_DETERMINACIONES;
		
		private string _ARTI_PNT_METODOLOGIA;
		
		private System.Nullable<int> _DEPA_ID;
		
		public MODELOS_DETALLE_Q2Result()
		{
		}
		
		[Column(Storage="_ARTI_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ARTI_ID
		{
			get
			{
				return this._ARTI_ID;
			}
			set
			{
				if ((this._ARTI_ID != value))
				{
					this._ARTI_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DESCRIPCION", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string ARTI_DESCRIPCION
		{
			get
			{
				return this._ARTI_DESCRIPCION;
			}
			set
			{
				if ((this._ARTI_DESCRIPCION != value))
				{
					this._ARTI_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int NOT NULL")]
		public int ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_ES_HIBRIDO", DbType="Bit")]
		public System.Nullable<bool> ES_HIBRIDO
		{
			get
			{
				return this._ES_HIBRIDO;
			}
			set
			{
				if ((this._ES_HIBRIDO != value))
				{
					this._ES_HIBRIDO = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DETERMINACIONES", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_DETERMINACIONES
		{
			get
			{
				return this._ARTI_DETERMINACIONES;
			}
			set
			{
				if ((this._ARTI_DETERMINACIONES != value))
				{
					this._ARTI_DETERMINACIONES = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_PNT_METODOLOGIA", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_PNT_METODOLOGIA
		{
			get
			{
				return this._ARTI_PNT_METODOLOGIA;
			}
			set
			{
				if ((this._ARTI_PNT_METODOLOGIA != value))
				{
					this._ARTI_PNT_METODOLOGIA = value;
				}
			}
		}
		
		[Column(Storage="_DEPA_ID", DbType="Int")]
		public System.Nullable<int> DEPA_ID
		{
			get
			{
				return this._DEPA_ID;
			}
			set
			{
				if ((this._DEPA_ID != value))
				{
					this._DEPA_ID = value;
				}
			}
		}
	}
	
	public partial class TIPANA_MATRIZ_CON_Q2Result
	{
		
		private string _TIPANA_ID;
		
		private string _TIPANA_DESCRIPCION;
		
		public TIPANA_MATRIZ_CON_Q2Result()
		{
		}
		
		[Column(Storage="_TIPANA_ID", DbType="VarChar(6)")]
		public string TIPANA_ID
		{
			get
			{
				return this._TIPANA_ID;
			}
			set
			{
				if ((this._TIPANA_ID != value))
				{
					this._TIPANA_ID = value;
				}
			}
		}
		
		[Column(Storage="_TIPANA_DESCRIPCION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TIPANA_DESCRIPCION
		{
			get
			{
				return this._TIPANA_DESCRIPCION;
			}
			set
			{
				if ((this._TIPANA_DESCRIPCION != value))
				{
					this._TIPANA_DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class DETERMINACIONES_DETALLE_Q2Result
	{
		
		private string _ARTI_ID;
		
		private string _ARTI_DESCRIPCION;
		
		private int _ARTI_ID1;
		
		private string _ARTI_DETERMINACIONES;
		
		private string _ARTI_PNT_METODOLOGIA;
		
		private string _TIPAR_ID;
		
		private int _DEPA_ID;
		
		public DETERMINACIONES_DETALLE_Q2Result()
		{
		}
		
		[Column(Storage="_ARTI_ID", DbType="VarChar(15)")]
		public string ARTI_ID
		{
			get
			{
				return this._ARTI_ID;
			}
			set
			{
				if ((this._ARTI_ID != value))
				{
					this._ARTI_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DESCRIPCION", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string ARTI_DESCRIPCION
		{
			get
			{
				return this._ARTI_DESCRIPCION;
			}
			set
			{
				if ((this._ARTI_DESCRIPCION != value))
				{
					this._ARTI_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int NOT NULL")]
		public int ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DETERMINACIONES", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_DETERMINACIONES
		{
			get
			{
				return this._ARTI_DETERMINACIONES;
			}
			set
			{
				if ((this._ARTI_DETERMINACIONES != value))
				{
					this._ARTI_DETERMINACIONES = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_PNT_METODOLOGIA", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_PNT_METODOLOGIA
		{
			get
			{
				return this._ARTI_PNT_METODOLOGIA;
			}
			set
			{
				if ((this._ARTI_PNT_METODOLOGIA != value))
				{
					this._ARTI_PNT_METODOLOGIA = value;
				}
			}
		}
		
		[Column(Storage="_TIPAR_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TIPAR_ID
		{
			get
			{
				return this._TIPAR_ID;
			}
			set
			{
				if ((this._TIPAR_ID != value))
				{
					this._TIPAR_ID = value;
				}
			}
		}
		
		[Column(Storage="_DEPA_ID", DbType="Int NOT NULL")]
		public int DEPA_ID
		{
			get
			{
				return this._DEPA_ID;
			}
			set
			{
				if ((this._DEPA_ID != value))
				{
					this._DEPA_ID = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_DETERMINACIONES_BY_TIPO_ANALISISResult
	{
		
		private string _ARTI_ID;
		
		private string _ARTI_DESCRIPCION;
		
		private int _ARTI_ID1;
		
		private string _ARTI_DETERMINACIONES;
		
		private string _ARTI_PNT_METODOLOGIA;
		
		private string _TIPAR_ID;
		
		private int _DEPA_ID;
		
		public Q2_GET_DETERMINACIONES_BY_TIPO_ANALISISResult()
		{
		}
		
		[Column(Storage="_ARTI_ID", DbType="VarChar(15)")]
		public string ARTI_ID
		{
			get
			{
				return this._ARTI_ID;
			}
			set
			{
				if ((this._ARTI_ID != value))
				{
					this._ARTI_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DESCRIPCION", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string ARTI_DESCRIPCION
		{
			get
			{
				return this._ARTI_DESCRIPCION;
			}
			set
			{
				if ((this._ARTI_DESCRIPCION != value))
				{
					this._ARTI_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int NOT NULL")]
		public int ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DETERMINACIONES", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_DETERMINACIONES
		{
			get
			{
				return this._ARTI_DETERMINACIONES;
			}
			set
			{
				if ((this._ARTI_DETERMINACIONES != value))
				{
					this._ARTI_DETERMINACIONES = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_PNT_METODOLOGIA", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_PNT_METODOLOGIA
		{
			get
			{
				return this._ARTI_PNT_METODOLOGIA;
			}
			set
			{
				if ((this._ARTI_PNT_METODOLOGIA != value))
				{
					this._ARTI_PNT_METODOLOGIA = value;
				}
			}
		}
		
		[Column(Storage="_TIPAR_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TIPAR_ID
		{
			get
			{
				return this._TIPAR_ID;
			}
			set
			{
				if ((this._TIPAR_ID != value))
				{
					this._TIPAR_ID = value;
				}
			}
		}
		
		[Column(Storage="_DEPA_ID", DbType="Int NOT NULL")]
		public int DEPA_ID
		{
			get
			{
				return this._DEPA_ID;
			}
			set
			{
				if ((this._DEPA_ID != value))
				{
					this._DEPA_ID = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_MODELOS_BY_TIPO_ANALISISResult
	{
		
		private string _ARTI_ID;
		
		private string _ARTI_DESCRIPCION;
		
		private int _ARTI_ID1;
		
		private System.Nullable<bool> _ES_HIBRIDO;
		
		private string _ARTI_DETERMINACIONES;
		
		private string _ARTI_PNT_METODOLOGIA;
		
		private System.Nullable<int> _DEPA_ID;
		
		public Q2_GET_MODELOS_BY_TIPO_ANALISISResult()
		{
		}
		
		[Column(Storage="_ARTI_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ARTI_ID
		{
			get
			{
				return this._ARTI_ID;
			}
			set
			{
				if ((this._ARTI_ID != value))
				{
					this._ARTI_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DESCRIPCION", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string ARTI_DESCRIPCION
		{
			get
			{
				return this._ARTI_DESCRIPCION;
			}
			set
			{
				if ((this._ARTI_DESCRIPCION != value))
				{
					this._ARTI_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int NOT NULL")]
		public int ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_ES_HIBRIDO", DbType="Bit")]
		public System.Nullable<bool> ES_HIBRIDO
		{
			get
			{
				return this._ES_HIBRIDO;
			}
			set
			{
				if ((this._ES_HIBRIDO != value))
				{
					this._ES_HIBRIDO = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DETERMINACIONES", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_DETERMINACIONES
		{
			get
			{
				return this._ARTI_DETERMINACIONES;
			}
			set
			{
				if ((this._ARTI_DETERMINACIONES != value))
				{
					this._ARTI_DETERMINACIONES = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_PNT_METODOLOGIA", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_PNT_METODOLOGIA
		{
			get
			{
				return this._ARTI_PNT_METODOLOGIA;
			}
			set
			{
				if ((this._ARTI_PNT_METODOLOGIA != value))
				{
					this._ARTI_PNT_METODOLOGIA = value;
				}
			}
		}
		
		[Column(Storage="_DEPA_ID", DbType="Int")]
		public System.Nullable<int> DEPA_ID
		{
			get
			{
				return this._DEPA_ID;
			}
			set
			{
				if ((this._DEPA_ID != value))
				{
					this._DEPA_ID = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_ARTICULOS_CARGO_BY_TIPO_ANALISISResult
	{
		
		private string _ARTI_ID;
		
		private string _ARTI_DESCRIPCION;
		
		private int _ARTI_ID1;
		
		private string _TIPAR_ID;
		
		public Q2_GET_ARTICULOS_CARGO_BY_TIPO_ANALISISResult()
		{
		}
		
		[Column(Storage="_ARTI_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ARTI_ID
		{
			get
			{
				return this._ARTI_ID;
			}
			set
			{
				if ((this._ARTI_ID != value))
				{
					this._ARTI_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DESCRIPCION", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string ARTI_DESCRIPCION
		{
			get
			{
				return this._ARTI_DESCRIPCION;
			}
			set
			{
				if ((this._ARTI_DESCRIPCION != value))
				{
					this._ARTI_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int NOT NULL")]
		public int ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_TIPAR_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TIPAR_ID
		{
			get
			{
				return this._TIPAR_ID;
			}
			set
			{
				if ((this._TIPAR_ID != value))
				{
					this._TIPAR_ID = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_ARTICULOS_CARGO_SERVICIOS_E_INFORMESResult
	{
		
		private string _ARTI_ID;
		
		private string _ARTI_DESCRIPCION;
		
		private int _ARTI_ID1;
		
		private string _TIPAR_ID;
		
		public Q2_GET_ARTICULOS_CARGO_SERVICIOS_E_INFORMESResult()
		{
		}
		
		[Column(Storage="_ARTI_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ARTI_ID
		{
			get
			{
				return this._ARTI_ID;
			}
			set
			{
				if ((this._ARTI_ID != value))
				{
					this._ARTI_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DESCRIPCION", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string ARTI_DESCRIPCION
		{
			get
			{
				return this._ARTI_DESCRIPCION;
			}
			set
			{
				if ((this._ARTI_DESCRIPCION != value))
				{
					this._ARTI_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int NOT NULL")]
		public int ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_TIPAR_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TIPAR_ID
		{
			get
			{
				return this._TIPAR_ID;
			}
			set
			{
				if ((this._TIPAR_ID != value))
				{
					this._TIPAR_ID = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_BLOQUES_GRUPO_BY_CLIENTEResult
	{
		
		private string _DOCU_ID;
		
		private string _PRESUV_ID;
		
		private string _ESTDOC_ID;
		
		private int _BLOQUE_ID;
		
		private string _FAMIL_ID;
		
		private string _FAMIL_DESCRIPCION;
		
		private string _TITULO;
		
		private string _REFERENCIA_CLIENTE;
		
		private string _FECHA_CREACION;
		
		private string _CLIE_DESCRIPCION;
		
		public Q2_GET_BLOQUES_GRUPO_BY_CLIENTEResult()
		{
		}
		
		[Column(Storage="_DOCU_ID", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DOCU_ID
		{
			get
			{
				return this._DOCU_ID;
			}
			set
			{
				if ((this._DOCU_ID != value))
				{
					this._DOCU_ID = value;
				}
			}
		}
		
		[Column(Storage="_PRESUV_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string PRESUV_ID
		{
			get
			{
				return this._PRESUV_ID;
			}
			set
			{
				if ((this._PRESUV_ID != value))
				{
					this._PRESUV_ID = value;
				}
			}
		}
		
		[Column(Storage="_ESTDOC_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string ESTDOC_ID
		{
			get
			{
				return this._ESTDOC_ID;
			}
			set
			{
				if ((this._ESTDOC_ID != value))
				{
					this._ESTDOC_ID = value;
				}
			}
		}
		
		[Column(Storage="_BLOQUE_ID", DbType="Int NOT NULL")]
		public int BLOQUE_ID
		{
			get
			{
				return this._BLOQUE_ID;
			}
			set
			{
				if ((this._BLOQUE_ID != value))
				{
					this._BLOQUE_ID = value;
				}
			}
		}
		
		[Column(Storage="_FAMIL_ID", DbType="VarChar(15)")]
		public string FAMIL_ID
		{
			get
			{
				return this._FAMIL_ID;
			}
			set
			{
				if ((this._FAMIL_ID != value))
				{
					this._FAMIL_ID = value;
				}
			}
		}
		
		[Column(Storage="_FAMIL_DESCRIPCION", DbType="VarChar(50)")]
		public string FAMIL_DESCRIPCION
		{
			get
			{
				return this._FAMIL_DESCRIPCION;
			}
			set
			{
				if ((this._FAMIL_DESCRIPCION != value))
				{
					this._FAMIL_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_TITULO", DbType="VarChar(120)")]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this._TITULO = value;
				}
			}
		}
		
		[Column(Storage="_REFERENCIA_CLIENTE", DbType="VarChar(35)")]
		public string REFERENCIA_CLIENTE
		{
			get
			{
				return this._REFERENCIA_CLIENTE;
			}
			set
			{
				if ((this._REFERENCIA_CLIENTE != value))
				{
					this._REFERENCIA_CLIENTE = value;
				}
			}
		}
		
		[Column(Storage="_FECHA_CREACION", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string FECHA_CREACION
		{
			get
			{
				return this._FECHA_CREACION;
			}
			set
			{
				if ((this._FECHA_CREACION != value))
				{
					this._FECHA_CREACION = value;
				}
			}
		}
		
		[Column(Storage="_CLIE_DESCRIPCION", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CLIE_DESCRIPCION
		{
			get
			{
				return this._CLIE_DESCRIPCION;
			}
			set
			{
				if ((this._CLIE_DESCRIPCION != value))
				{
					this._CLIE_DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_DETALLE_BY_BLOQUEResult
	{
		
		private string _LIDO_ID;
		
		private int _PRESUVL_LINEA;
		
		private int _PRESUVL_SUBLINEA;
		
		private System.Nullable<int> _ARTI_ID1;
		
		private string _PRESUVL_DESCRIPCION;
		
		private decimal _PRESUVL_CANTIDAD;
		
		private string _UNID_ID;
		
		private string _UNID_DESCRIPCION;
		
		private decimal _PRESUVL_PRECIO;
		
		private System.Nullable<int> _GRDE_ID;
		
		private string _GRDE_DESCRIPCION;
		
		private System.Nullable<int> _COMP_ID;
		
		private string _ARTI_DETERMINACIONES;
		
		private string _ARTI_PNT_METODOLOGIA;
		
		public Q2_GET_DETALLE_BY_BLOQUEResult()
		{
		}
		
		[Column(Storage="_LIDO_ID", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string LIDO_ID
		{
			get
			{
				return this._LIDO_ID;
			}
			set
			{
				if ((this._LIDO_ID != value))
				{
					this._LIDO_ID = value;
				}
			}
		}
		
		[Column(Storage="_PRESUVL_LINEA", DbType="Int NOT NULL")]
		public int PRESUVL_LINEA
		{
			get
			{
				return this._PRESUVL_LINEA;
			}
			set
			{
				if ((this._PRESUVL_LINEA != value))
				{
					this._PRESUVL_LINEA = value;
				}
			}
		}
		
		[Column(Storage="_PRESUVL_SUBLINEA", DbType="Int NOT NULL")]
		public int PRESUVL_SUBLINEA
		{
			get
			{
				return this._PRESUVL_SUBLINEA;
			}
			set
			{
				if ((this._PRESUVL_SUBLINEA != value))
				{
					this._PRESUVL_SUBLINEA = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int")]
		public System.Nullable<int> ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_PRESUVL_DESCRIPCION", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PRESUVL_DESCRIPCION
		{
			get
			{
				return this._PRESUVL_DESCRIPCION;
			}
			set
			{
				if ((this._PRESUVL_DESCRIPCION != value))
				{
					this._PRESUVL_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_PRESUVL_CANTIDAD", DbType="Decimal(0,0) NOT NULL")]
		public decimal PRESUVL_CANTIDAD
		{
			get
			{
				return this._PRESUVL_CANTIDAD;
			}
			set
			{
				if ((this._PRESUVL_CANTIDAD != value))
				{
					this._PRESUVL_CANTIDAD = value;
				}
			}
		}
		
		[Column(Storage="_UNID_ID", DbType="VarChar(3)")]
		public string UNID_ID
		{
			get
			{
				return this._UNID_ID;
			}
			set
			{
				if ((this._UNID_ID != value))
				{
					this._UNID_ID = value;
				}
			}
		}
		
		[Column(Storage="_UNID_DESCRIPCION", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string UNID_DESCRIPCION
		{
			get
			{
				return this._UNID_DESCRIPCION;
			}
			set
			{
				if ((this._UNID_DESCRIPCION != value))
				{
					this._UNID_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_PRESUVL_PRECIO", DbType="Decimal(0,0) NOT NULL")]
		public decimal PRESUVL_PRECIO
		{
			get
			{
				return this._PRESUVL_PRECIO;
			}
			set
			{
				if ((this._PRESUVL_PRECIO != value))
				{
					this._PRESUVL_PRECIO = value;
				}
			}
		}
		
		[Column(Storage="_GRDE_ID", DbType="Int")]
		public System.Nullable<int> GRDE_ID
		{
			get
			{
				return this._GRDE_ID;
			}
			set
			{
				if ((this._GRDE_ID != value))
				{
					this._GRDE_ID = value;
				}
			}
		}
		
		[Column(Storage="_GRDE_DESCRIPCION", DbType="VarChar(50)")]
		public string GRDE_DESCRIPCION
		{
			get
			{
				return this._GRDE_DESCRIPCION;
			}
			set
			{
				if ((this._GRDE_DESCRIPCION != value))
				{
					this._GRDE_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_COMP_ID", DbType="Int")]
		public System.Nullable<int> COMP_ID
		{
			get
			{
				return this._COMP_ID;
			}
			set
			{
				if ((this._COMP_ID != value))
				{
					this._COMP_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DETERMINACIONES", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_DETERMINACIONES
		{
			get
			{
				return this._ARTI_DETERMINACIONES;
			}
			set
			{
				if ((this._ARTI_DETERMINACIONES != value))
				{
					this._ARTI_DETERMINACIONES = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_PNT_METODOLOGIA", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_PNT_METODOLOGIA
		{
			get
			{
				return this._ARTI_PNT_METODOLOGIA;
			}
			set
			{
				if ((this._ARTI_PNT_METODOLOGIA != value))
				{
					this._ARTI_PNT_METODOLOGIA = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_ASOCIADOSResult
	{
		
		private string _ARTI_ID;
		
		private int _ARTI_ID1;
		
		private string _ARTI_DESCRIPCION;
		
		private string _ARTI_PNT_METODOLOGIA;
		
		private string _ARTI_DETERMINACIONES;
		
		private string _TIPAR_ID;
		
		private int _DEPA_ID;
		
		public Q2_GET_ASOCIADOSResult()
		{
		}
		
		[Column(Storage="_ARTI_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ARTI_ID
		{
			get
			{
				return this._ARTI_ID;
			}
			set
			{
				if ((this._ARTI_ID != value))
				{
					this._ARTI_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int NOT NULL")]
		public int ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DESCRIPCION", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string ARTI_DESCRIPCION
		{
			get
			{
				return this._ARTI_DESCRIPCION;
			}
			set
			{
				if ((this._ARTI_DESCRIPCION != value))
				{
					this._ARTI_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_PNT_METODOLOGIA", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_PNT_METODOLOGIA
		{
			get
			{
				return this._ARTI_PNT_METODOLOGIA;
			}
			set
			{
				if ((this._ARTI_PNT_METODOLOGIA != value))
				{
					this._ARTI_PNT_METODOLOGIA = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_DETERMINACIONES", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ARTI_DETERMINACIONES
		{
			get
			{
				return this._ARTI_DETERMINACIONES;
			}
			set
			{
				if ((this._ARTI_DETERMINACIONES != value))
				{
					this._ARTI_DETERMINACIONES = value;
				}
			}
		}
		
		[Column(Storage="_TIPAR_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TIPAR_ID
		{
			get
			{
				return this._TIPAR_ID;
			}
			set
			{
				if ((this._TIPAR_ID != value))
				{
					this._TIPAR_ID = value;
				}
			}
		}
		
		[Column(Storage="_DEPA_ID", DbType="Int NOT NULL")]
		public int DEPA_ID
		{
			get
			{
				return this._DEPA_ID;
			}
			set
			{
				if ((this._DEPA_ID != value))
				{
					this._DEPA_ID = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_DETALLE_BY_PEDIDO2Result
	{
		
		private string _DOCU_ID;
		
		private string _PEDID_ID;
		
		private int _PEDIDL_LINEA;
		
		private int _PEDIDL_SUBLINEA;
		
		private string _LIDO_ID;
		
		private string _PEDIDL_DESCRIPCION;
		
		private decimal _PEDIDL_CANTIDAD;
		
		private decimal _PEDIDL_PRECIO;
		
		private System.Nullable<int> _GRDE_ID;
		
		private string _ESTDOC_ID;
		
		private string _UNID_ID;
		
		private string _DOCU_ID_ORIGEN;
		
		private string _DOCU_NUMERO_ORIGEN;
		
		private System.Nullable<int> _DOCU_LINEA_ORIGEN;
		
		private System.Nullable<int> _DOCU_SUBLINEA_ORIGEN;
		
		private char _PEDIDL_FLUJOC;
		
		private char _PEDIDL_FLUJOL;
		
		private System.Nullable<int> _COMP_ID;
		
		private System.Nullable<int> _ARTI_ID1;
		
		private string _PEDIDL_FECHAD_APLIC;
		
		private string _PEDIDL_FECHAH_APLIC;
		
		private string _UNID_DESCRIPCION;
		
		private string _GRDE_DESCRIPCION;
		
		private int _DEPA_ID;
		
		public Q2_GET_DETALLE_BY_PEDIDO2Result()
		{
		}
		
		[Column(Storage="_DOCU_ID", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DOCU_ID
		{
			get
			{
				return this._DOCU_ID;
			}
			set
			{
				if ((this._DOCU_ID != value))
				{
					this._DOCU_ID = value;
				}
			}
		}
		
		[Column(Storage="_PEDID_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string PEDID_ID
		{
			get
			{
				return this._PEDID_ID;
			}
			set
			{
				if ((this._PEDID_ID != value))
				{
					this._PEDID_ID = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_LINEA", DbType="Int NOT NULL")]
		public int PEDIDL_LINEA
		{
			get
			{
				return this._PEDIDL_LINEA;
			}
			set
			{
				if ((this._PEDIDL_LINEA != value))
				{
					this._PEDIDL_LINEA = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_SUBLINEA", DbType="Int NOT NULL")]
		public int PEDIDL_SUBLINEA
		{
			get
			{
				return this._PEDIDL_SUBLINEA;
			}
			set
			{
				if ((this._PEDIDL_SUBLINEA != value))
				{
					this._PEDIDL_SUBLINEA = value;
				}
			}
		}
		
		[Column(Storage="_LIDO_ID", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string LIDO_ID
		{
			get
			{
				return this._LIDO_ID;
			}
			set
			{
				if ((this._LIDO_ID != value))
				{
					this._LIDO_ID = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_DESCRIPCION", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PEDIDL_DESCRIPCION
		{
			get
			{
				return this._PEDIDL_DESCRIPCION;
			}
			set
			{
				if ((this._PEDIDL_DESCRIPCION != value))
				{
					this._PEDIDL_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_CANTIDAD", DbType="Decimal(0,0) NOT NULL")]
		public decimal PEDIDL_CANTIDAD
		{
			get
			{
				return this._PEDIDL_CANTIDAD;
			}
			set
			{
				if ((this._PEDIDL_CANTIDAD != value))
				{
					this._PEDIDL_CANTIDAD = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_PRECIO", DbType="Decimal(0,0) NOT NULL")]
		public decimal PEDIDL_PRECIO
		{
			get
			{
				return this._PEDIDL_PRECIO;
			}
			set
			{
				if ((this._PEDIDL_PRECIO != value))
				{
					this._PEDIDL_PRECIO = value;
				}
			}
		}
		
		[Column(Storage="_GRDE_ID", DbType="Int")]
		public System.Nullable<int> GRDE_ID
		{
			get
			{
				return this._GRDE_ID;
			}
			set
			{
				if ((this._GRDE_ID != value))
				{
					this._GRDE_ID = value;
				}
			}
		}
		
		[Column(Storage="_ESTDOC_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string ESTDOC_ID
		{
			get
			{
				return this._ESTDOC_ID;
			}
			set
			{
				if ((this._ESTDOC_ID != value))
				{
					this._ESTDOC_ID = value;
				}
			}
		}
		
		[Column(Storage="_UNID_ID", DbType="VarChar(3)")]
		public string UNID_ID
		{
			get
			{
				return this._UNID_ID;
			}
			set
			{
				if ((this._UNID_ID != value))
				{
					this._UNID_ID = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_ID_ORIGEN", DbType="VarChar(6)")]
		public string DOCU_ID_ORIGEN
		{
			get
			{
				return this._DOCU_ID_ORIGEN;
			}
			set
			{
				if ((this._DOCU_ID_ORIGEN != value))
				{
					this._DOCU_ID_ORIGEN = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_NUMERO_ORIGEN", DbType="VarChar(15)")]
		public string DOCU_NUMERO_ORIGEN
		{
			get
			{
				return this._DOCU_NUMERO_ORIGEN;
			}
			set
			{
				if ((this._DOCU_NUMERO_ORIGEN != value))
				{
					this._DOCU_NUMERO_ORIGEN = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_LINEA_ORIGEN", DbType="Int")]
		public System.Nullable<int> DOCU_LINEA_ORIGEN
		{
			get
			{
				return this._DOCU_LINEA_ORIGEN;
			}
			set
			{
				if ((this._DOCU_LINEA_ORIGEN != value))
				{
					this._DOCU_LINEA_ORIGEN = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_SUBLINEA_ORIGEN", DbType="Int")]
		public System.Nullable<int> DOCU_SUBLINEA_ORIGEN
		{
			get
			{
				return this._DOCU_SUBLINEA_ORIGEN;
			}
			set
			{
				if ((this._DOCU_SUBLINEA_ORIGEN != value))
				{
					this._DOCU_SUBLINEA_ORIGEN = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_FLUJOC", DbType="VarChar(1) NOT NULL")]
		public char PEDIDL_FLUJOC
		{
			get
			{
				return this._PEDIDL_FLUJOC;
			}
			set
			{
				if ((this._PEDIDL_FLUJOC != value))
				{
					this._PEDIDL_FLUJOC = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_FLUJOL", DbType="VarChar(1) NOT NULL")]
		public char PEDIDL_FLUJOL
		{
			get
			{
				return this._PEDIDL_FLUJOL;
			}
			set
			{
				if ((this._PEDIDL_FLUJOL != value))
				{
					this._PEDIDL_FLUJOL = value;
				}
			}
		}
		
		[Column(Storage="_COMP_ID", DbType="Int")]
		public System.Nullable<int> COMP_ID
		{
			get
			{
				return this._COMP_ID;
			}
			set
			{
				if ((this._COMP_ID != value))
				{
					this._COMP_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int")]
		public System.Nullable<int> ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_FECHAD_APLIC", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PEDIDL_FECHAD_APLIC
		{
			get
			{
				return this._PEDIDL_FECHAD_APLIC;
			}
			set
			{
				if ((this._PEDIDL_FECHAD_APLIC != value))
				{
					this._PEDIDL_FECHAD_APLIC = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_FECHAH_APLIC", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PEDIDL_FECHAH_APLIC
		{
			get
			{
				return this._PEDIDL_FECHAH_APLIC;
			}
			set
			{
				if ((this._PEDIDL_FECHAH_APLIC != value))
				{
					this._PEDIDL_FECHAH_APLIC = value;
				}
			}
		}
		
		[Column(Storage="_UNID_DESCRIPCION", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string UNID_DESCRIPCION
		{
			get
			{
				return this._UNID_DESCRIPCION;
			}
			set
			{
				if ((this._UNID_DESCRIPCION != value))
				{
					this._UNID_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_GRDE_DESCRIPCION", DbType="VarChar(50)")]
		public string GRDE_DESCRIPCION
		{
			get
			{
				return this._GRDE_DESCRIPCION;
			}
			set
			{
				if ((this._GRDE_DESCRIPCION != value))
				{
					this._GRDE_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_DEPA_ID", DbType="Int NOT NULL")]
		public int DEPA_ID
		{
			get
			{
				return this._DEPA_ID;
			}
			set
			{
				if ((this._DEPA_ID != value))
				{
					this._DEPA_ID = value;
				}
			}
		}
	}
	
	public partial class Q2_GET_COMP_IVA_CLIENTEResult
	{
		
		private System.Nullable<int> _COMP_ID;
		
		public Q2_GET_COMP_IVA_CLIENTEResult()
		{
		}
		
		[Column(Storage="_COMP_ID", DbType="Int")]
		public System.Nullable<int> COMP_ID
		{
			get
			{
				return this._COMP_ID;
			}
			set
			{
				if ((this._COMP_ID != value))
				{
					this._COMP_ID = value;
				}
			}
		}
	}
	
	public partial class CLIENTES_COND_PRECIO2Result
	{
		
		private System.Nullable<int> _ESCA_ID;
		
		private decimal _PRECIO;
		
		private System.Nullable<int> _GRDE_ID;
		
		private System.Nullable<decimal> _ESCAL_DESDE;
		
		private System.Nullable<decimal> _ESCAL_HASTA;
		
		private System.Nullable<decimal> _ESCAL_VALOR;
		
		private System.Nullable<decimal> _ESCAL_VALOR1;
		
		private System.Nullable<decimal> _TRAM_DESDE;
		
		private System.Nullable<decimal> _TRAM_HASTA;
		
		private string _TABLA_ESCALA;
		
		private string _CAMPO_ESCALA;
		
		private string _TABLA_TRAMO;
		
		private string _CAMPO_TRAMO;
		
		public CLIENTES_COND_PRECIO2Result()
		{
		}
		
		[Column(Storage="_ESCA_ID", DbType="Int")]
		public System.Nullable<int> ESCA_ID
		{
			get
			{
				return this._ESCA_ID;
			}
			set
			{
				if ((this._ESCA_ID != value))
				{
					this._ESCA_ID = value;
				}
			}
		}
		
		[Column(Storage="_PRECIO", DbType="Decimal(0,0) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[Column(Storage="_GRDE_ID", DbType="Int")]
		public System.Nullable<int> GRDE_ID
		{
			get
			{
				return this._GRDE_ID;
			}
			set
			{
				if ((this._GRDE_ID != value))
				{
					this._GRDE_ID = value;
				}
			}
		}
		
		[Column(Storage="_ESCAL_DESDE", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> ESCAL_DESDE
		{
			get
			{
				return this._ESCAL_DESDE;
			}
			set
			{
				if ((this._ESCAL_DESDE != value))
				{
					this._ESCAL_DESDE = value;
				}
			}
		}
		
		[Column(Storage="_ESCAL_HASTA", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> ESCAL_HASTA
		{
			get
			{
				return this._ESCAL_HASTA;
			}
			set
			{
				if ((this._ESCAL_HASTA != value))
				{
					this._ESCAL_HASTA = value;
				}
			}
		}
		
		[Column(Storage="_ESCAL_VALOR", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> ESCAL_VALOR
		{
			get
			{
				return this._ESCAL_VALOR;
			}
			set
			{
				if ((this._ESCAL_VALOR != value))
				{
					this._ESCAL_VALOR = value;
				}
			}
		}
		
		[Column(Storage="_ESCAL_VALOR1", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> ESCAL_VALOR1
		{
			get
			{
				return this._ESCAL_VALOR1;
			}
			set
			{
				if ((this._ESCAL_VALOR1 != value))
				{
					this._ESCAL_VALOR1 = value;
				}
			}
		}
		
		[Column(Storage="_TRAM_DESDE", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> TRAM_DESDE
		{
			get
			{
				return this._TRAM_DESDE;
			}
			set
			{
				if ((this._TRAM_DESDE != value))
				{
					this._TRAM_DESDE = value;
				}
			}
		}
		
		[Column(Storage="_TRAM_HASTA", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> TRAM_HASTA
		{
			get
			{
				return this._TRAM_HASTA;
			}
			set
			{
				if ((this._TRAM_HASTA != value))
				{
					this._TRAM_HASTA = value;
				}
			}
		}
		
		[Column(Storage="_TABLA_ESCALA", DbType="VarChar(30)")]
		public string TABLA_ESCALA
		{
			get
			{
				return this._TABLA_ESCALA;
			}
			set
			{
				if ((this._TABLA_ESCALA != value))
				{
					this._TABLA_ESCALA = value;
				}
			}
		}
		
		[Column(Storage="_CAMPO_ESCALA", DbType="VarChar(30)")]
		public string CAMPO_ESCALA
		{
			get
			{
				return this._CAMPO_ESCALA;
			}
			set
			{
				if ((this._CAMPO_ESCALA != value))
				{
					this._CAMPO_ESCALA = value;
				}
			}
		}
		
		[Column(Storage="_TABLA_TRAMO", DbType="VarChar(30)")]
		public string TABLA_TRAMO
		{
			get
			{
				return this._TABLA_TRAMO;
			}
			set
			{
				if ((this._TABLA_TRAMO != value))
				{
					this._TABLA_TRAMO = value;
				}
			}
		}
		
		[Column(Storage="_CAMPO_TRAMO", DbType="VarChar(30)")]
		public string CAMPO_TRAMO
		{
			get
			{
				return this._CAMPO_TRAMO;
			}
			set
			{
				if ((this._CAMPO_TRAMO != value))
				{
					this._CAMPO_TRAMO = value;
				}
			}
		}
	}
	
	public partial class Q2_PEDIDOSV_LI_SELResult
	{
		
		private string _DOCU_ID;
		
		private string _PEDID_ID;
		
		private int _PEDIDL_LINEA;
		
		private int _PEDIDL_SUBLINEA;
		
		private string _LIDO_ID;
		
		private string _PEDIDL_DESCRIPCION;
		
		private decimal _PEDIDL_CANTIDAD;
		
		private decimal _PEDIDL_PRECIO;
		
		private System.Nullable<int> _GRDE_ID;
		
		private string _ESTDOC_ID;
		
		private string _UNID_ID;
		
		private string _DOCU_ID_ORIGEN;
		
		private string _DOCU_NUMERO_ORIGEN;
		
		private System.Nullable<int> _DOCU_LINEA_ORIGEN;
		
		private System.Nullable<int> _DOCU_SUBLINEA_ORIGEN;
		
		private string _PEDIDL_FLUJOC;
		
		private string _PEDIDL_FLUJOL;
		
		private System.Nullable<int> _COMP_ID;
		
		private System.Nullable<int> _ARTI_ID1;
		
		private string _PEDIDL_FECHAD_APLIC;
		
		private string _PEDIDL_FECHAH_APLIC;
		
		public Q2_PEDIDOSV_LI_SELResult()
		{
		}
		
		[Column(Storage="_DOCU_ID", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DOCU_ID
		{
			get
			{
				return this._DOCU_ID;
			}
			set
			{
				if ((this._DOCU_ID != value))
				{
					this._DOCU_ID = value;
				}
			}
		}
		
		[Column(Storage="_PEDID_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string PEDID_ID
		{
			get
			{
				return this._PEDID_ID;
			}
			set
			{
				if ((this._PEDID_ID != value))
				{
					this._PEDID_ID = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_LINEA", DbType="Int NOT NULL")]
		public int PEDIDL_LINEA
		{
			get
			{
				return this._PEDIDL_LINEA;
			}
			set
			{
				if ((this._PEDIDL_LINEA != value))
				{
					this._PEDIDL_LINEA = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_SUBLINEA", DbType="Int NOT NULL")]
		public int PEDIDL_SUBLINEA
		{
			get
			{
				return this._PEDIDL_SUBLINEA;
			}
			set
			{
				if ((this._PEDIDL_SUBLINEA != value))
				{
					this._PEDIDL_SUBLINEA = value;
				}
			}
		}
		
		[Column(Storage="_LIDO_ID", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string LIDO_ID
		{
			get
			{
				return this._LIDO_ID;
			}
			set
			{
				if ((this._LIDO_ID != value))
				{
					this._LIDO_ID = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_DESCRIPCION", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PEDIDL_DESCRIPCION
		{
			get
			{
				return this._PEDIDL_DESCRIPCION;
			}
			set
			{
				if ((this._PEDIDL_DESCRIPCION != value))
				{
					this._PEDIDL_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_CANTIDAD", DbType="Decimal(0,0) NOT NULL")]
		public decimal PEDIDL_CANTIDAD
		{
			get
			{
				return this._PEDIDL_CANTIDAD;
			}
			set
			{
				if ((this._PEDIDL_CANTIDAD != value))
				{
					this._PEDIDL_CANTIDAD = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_PRECIO", DbType="Decimal(0,0) NOT NULL")]
		public decimal PEDIDL_PRECIO
		{
			get
			{
				return this._PEDIDL_PRECIO;
			}
			set
			{
				if ((this._PEDIDL_PRECIO != value))
				{
					this._PEDIDL_PRECIO = value;
				}
			}
		}
		
		[Column(Storage="_GRDE_ID", DbType="Int")]
		public System.Nullable<int> GRDE_ID
		{
			get
			{
				return this._GRDE_ID;
			}
			set
			{
				if ((this._GRDE_ID != value))
				{
					this._GRDE_ID = value;
				}
			}
		}
		
		[Column(Storage="_ESTDOC_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string ESTDOC_ID
		{
			get
			{
				return this._ESTDOC_ID;
			}
			set
			{
				if ((this._ESTDOC_ID != value))
				{
					this._ESTDOC_ID = value;
				}
			}
		}
		
		[Column(Storage="_UNID_ID", DbType="VarChar(3)")]
		public string UNID_ID
		{
			get
			{
				return this._UNID_ID;
			}
			set
			{
				if ((this._UNID_ID != value))
				{
					this._UNID_ID = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_ID_ORIGEN", DbType="VarChar(6)")]
		public string DOCU_ID_ORIGEN
		{
			get
			{
				return this._DOCU_ID_ORIGEN;
			}
			set
			{
				if ((this._DOCU_ID_ORIGEN != value))
				{
					this._DOCU_ID_ORIGEN = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_NUMERO_ORIGEN", DbType="VarChar(15)")]
		public string DOCU_NUMERO_ORIGEN
		{
			get
			{
				return this._DOCU_NUMERO_ORIGEN;
			}
			set
			{
				if ((this._DOCU_NUMERO_ORIGEN != value))
				{
					this._DOCU_NUMERO_ORIGEN = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_LINEA_ORIGEN", DbType="Int")]
		public System.Nullable<int> DOCU_LINEA_ORIGEN
		{
			get
			{
				return this._DOCU_LINEA_ORIGEN;
			}
			set
			{
				if ((this._DOCU_LINEA_ORIGEN != value))
				{
					this._DOCU_LINEA_ORIGEN = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_SUBLINEA_ORIGEN", DbType="Int")]
		public System.Nullable<int> DOCU_SUBLINEA_ORIGEN
		{
			get
			{
				return this._DOCU_SUBLINEA_ORIGEN;
			}
			set
			{
				if ((this._DOCU_SUBLINEA_ORIGEN != value))
				{
					this._DOCU_SUBLINEA_ORIGEN = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_FLUJOC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PEDIDL_FLUJOC
		{
			get
			{
				return this._PEDIDL_FLUJOC;
			}
			set
			{
				if ((this._PEDIDL_FLUJOC != value))
				{
					this._PEDIDL_FLUJOC = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_FLUJOL", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PEDIDL_FLUJOL
		{
			get
			{
				return this._PEDIDL_FLUJOL;
			}
			set
			{
				if ((this._PEDIDL_FLUJOL != value))
				{
					this._PEDIDL_FLUJOL = value;
				}
			}
		}
		
		[Column(Storage="_COMP_ID", DbType="Int")]
		public System.Nullable<int> COMP_ID
		{
			get
			{
				return this._COMP_ID;
			}
			set
			{
				if ((this._COMP_ID != value))
				{
					this._COMP_ID = value;
				}
			}
		}
		
		[Column(Storage="_ARTI_ID1", DbType="Int")]
		public System.Nullable<int> ARTI_ID1
		{
			get
			{
				return this._ARTI_ID1;
			}
			set
			{
				if ((this._ARTI_ID1 != value))
				{
					this._ARTI_ID1 = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_FECHAD_APLIC", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PEDIDL_FECHAD_APLIC
		{
			get
			{
				return this._PEDIDL_FECHAD_APLIC;
			}
			set
			{
				if ((this._PEDIDL_FECHAD_APLIC != value))
				{
					this._PEDIDL_FECHAD_APLIC = value;
				}
			}
		}
		
		[Column(Storage="_PEDIDL_FECHAH_APLIC", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PEDIDL_FECHAH_APLIC
		{
			get
			{
				return this._PEDIDL_FECHAH_APLIC;
			}
			set
			{
				if ((this._PEDIDL_FECHAH_APLIC != value))
				{
					this._PEDIDL_FECHAH_APLIC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
