#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class PersonalConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PersonalConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PersonalConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonalConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonalConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonalConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.PERSONAL_CON_Q2")]
		public ISingleResult<PERSONAL_CON_Q2Result> PERSONAL_CON_Q2([Parameter(Name="PERS_NOMBRE", DbType="VarChar(50)")] string pERS_NOMBRE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERS_NOMBRE);
			return ((ISingleResult<PERSONAL_CON_Q2Result>)(result.ReturnValue));
		}
	}
	
	public partial class PERSONAL_CON_Q2Result
	{
		
		private int _PERS_ID;
		
		private string _PERS_NOMBRE;
		
		public PERSONAL_CON_Q2Result()
		{
		}
		
		[Column(Storage="_PERS_ID", DbType="Int NOT NULL")]
		public int PERS_ID
		{
			get
			{
				return this._PERS_ID;
			}
			set
			{
				if ((this._PERS_ID != value))
				{
					this._PERS_ID = value;
				}
			}
		}
		
		[Column(Storage="_PERS_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PERS_NOMBRE
		{
			get
			{
				return this._PERS_NOMBRE;
			}
			set
			{
				if ((this._PERS_NOMBRE != value))
				{
					this._PERS_NOMBRE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
