#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class PortesConsultaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PortesConsultaDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PortesConsultaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortesConsultaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortesConsultaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortesConsultaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.TIPOS_PORTE_CON")]
		public ISingleResult<TIPOS_PORTE_CONResult> TIPOS_PORTE_CON([Parameter(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, [Parameter(Name="USUARIO", DbType="VarChar(15)")] string uSUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, uSUARIO);
			return ((ISingleResult<TIPOS_PORTE_CONResult>)(result.ReturnValue));
		}
	}
	
	public partial class TIPOS_PORTE_CONResult
	{
		
		private string _TIPORT_ID;
		
		private string _TIPORT_DESCRIPCION;
		
		public TIPOS_PORTE_CONResult()
		{
		}
		
		[Column(Storage="_TIPORT_ID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TIPORT_ID
		{
			get
			{
				return this._TIPORT_ID;
			}
			set
			{
				if ((this._TIPORT_ID != value))
				{
					this._TIPORT_ID = value;
				}
			}
		}
		
		[Column(Storage="_TIPORT_DESCRIPCION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TIPORT_DESCRIPCION
		{
			get
			{
				return this._TIPORT_DESCRIPCION;
			}
			set
			{
				if ((this._TIPORT_DESCRIPCION != value))
				{
					this._TIPORT_DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
