#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentosVentas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class RegistroLaboratorioPedidoVDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public RegistroLaboratorioPedidoVDBDataContext() : 
				base(global::DocumentosVentas.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RegistroLaboratorioPedidoVDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RegistroLaboratorioPedidoVDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RegistroLaboratorioPedidoVDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RegistroLaboratorioPedidoVDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.REGISTROLAB_UPD1")]
		public int REGISTROLAB_UPD1(
					[Parameter(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, 
					[Parameter(Name="USUARIO", DbType="VarChar(15)")] string uSUARIO, 
					[Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, 
					[Parameter(Name="REGLAB_ID", DbType="VarChar(15)")] string rEGLAB_ID, 
					[Parameter(Name="REGLAB_FECHA", DbType="VarChar(10)")] string rEGLAB_FECHA, 
					[Parameter(Name="ARTI_ID1", DbType="Int")] System.Nullable<int> aRTI_ID1, 
					[Parameter(Name="REGLAB_ANOTACIONES", DbType="Text")] string rEGLAB_ANOTACIONES, 
					[Parameter(Name="REGLAB_XML", DbType="Text")] string rEGLAB_XML, 
					[Parameter(Name="SUREFERENCIA", DbType="VarChar(50)")] string sUREFERENCIA, 
					[Parameter(Name="CLIE_ID", DbType="Int")] System.Nullable<int> cLIE_ID, 
					[Parameter(Name="NIVURG_ID", DbType="Int")] System.Nullable<int> nIVURG_ID, 
					[Parameter(Name="REGLAB_HORA", DbType="VarChar(5)")] string rEGLAB_HORA, 
					[Parameter(Name="REGLAB_FECHAMUESTREO", DbType="VarChar(10)")] string rEGLAB_FECHAMUESTREO, 
					[Parameter(Name="REGLAB_HORAMUESTREO", DbType="VarChar(5)")] string rEGLAB_HORAMUESTREO, 
					[Parameter(Name="REGLAB_FECHAMAXIMA", DbType="VarChar(10)")] string rEGLAB_FECHAMAXIMA, 
					[Parameter(Name="REGLAB_HORAMAXIMA", DbType="VarChar(5)")] string rEGLAB_HORAMAXIMA, 
					[Parameter(Name="REGLAB_EMPRESAMUESTREO", DbType="VarChar(1)")] string rEGLAB_EMPRESAMUESTREO, 
					[Parameter(Name="REGLAB_MUESTREADOR", DbType="VarChar(50)")] string rEGLAB_MUESTREADOR, 
					[Parameter(Name="REGLAB_FECHARECOGIDA", DbType="VarChar(10)")] string rEGLAB_FECHARECOGIDA, 
					[Parameter(Name="REGLAB_HORARECOGIDA", DbType="VarChar(5)")] string rEGLAB_HORARECOGIDA, 
					[Parameter(Name="REGLAB_EMPRESARECOGIDA", DbType="VarChar(1)")] string rEGLAB_EMPRESARECOGIDA, 
					[Parameter(Name="REGLAB_RECOGEDOR", DbType="VarChar(50)")] string rEGLAB_RECOGEDOR, 
					[Parameter(Name="REGLAB_PERSONAENTRADA", DbType="Int")] System.Nullable<int> rEGLAB_PERSONAENTRADA, 
					[Parameter(Name="MUESTRA_DESCRIPCION", DbType="VarChar(70)")] string mUESTRA_DESCRIPCION, 
					[Parameter(Name="MUESTRA_REF1", DbType="VarChar(70)")] string mUESTRA_REF1, 
					[Parameter(Name="MUESTRA_REF2", DbType="VarChar(70)")] string mUESTRA_REF2, 
					[Parameter(Name="MUESTRA_REF3", DbType="VarChar(70)")] string mUESTRA_REF3, 
					[Parameter(Name="MUESTRA_OBSERVACIONES", DbType="VarChar(100)")] string mUESTRA_OBSERVACIONES, 
					[Parameter(Name="MUESTREADOR_PERS_ID", DbType="Int")] System.Nullable<int> mUESTREADOR_PERS_ID, 
					[Parameter(Name="RECOGEDOR_PERS_ID", DbType="Int")] System.Nullable<int> rECOGEDOR_PERS_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, uSUARIO, dOCU_ID, rEGLAB_ID, rEGLAB_FECHA, aRTI_ID1, rEGLAB_ANOTACIONES, rEGLAB_XML, sUREFERENCIA, cLIE_ID, nIVURG_ID, rEGLAB_HORA, rEGLAB_FECHAMUESTREO, rEGLAB_HORAMUESTREO, rEGLAB_FECHAMAXIMA, rEGLAB_HORAMAXIMA, rEGLAB_EMPRESAMUESTREO, rEGLAB_MUESTREADOR, rEGLAB_FECHARECOGIDA, rEGLAB_HORARECOGIDA, rEGLAB_EMPRESARECOGIDA, rEGLAB_RECOGEDOR, rEGLAB_PERSONAENTRADA, mUESTRA_DESCRIPCION, mUESTRA_REF1, mUESTRA_REF2, mUESTRA_REF3, mUESTRA_OBSERVACIONES, mUESTREADOR_PERS_ID, rECOGEDOR_PERS_ID);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.REGISTROLAB_INS2")]
		public int REGISTROLAB_INS2(
					[Parameter(Name="TIPO", DbType="SmallInt")] System.Nullable<short> tIPO, 
					[Parameter(Name="USUARIO", DbType="VarChar(15)")] string uSUARIO, 
					[Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID, 
					[Parameter(Name="REGLAB_ID", DbType="VarChar(15)")] ref string rEGLAB_ID, 
					[Parameter(Name="ESTDOC_ID", DbType="VarChar(3)")] string eSTDOC_ID, 
					[Parameter(Name="REGLAB_FECHA", DbType="VarChar(10)")] string rEGLAB_FECHA, 
					[Parameter(Name="DOCU_ID_ORIGEN", DbType="VarChar(6)")] string dOCU_ID_ORIGEN, 
					[Parameter(Name="DOCU_NUMERO_ORIGEN", DbType="VarChar(15)")] string dOCU_NUMERO_ORIGEN, 
					[Parameter(Name="ARTI_ID1", DbType="Int")] System.Nullable<int> aRTI_ID1, 
					[Parameter(Name="REGLAB_ANOTACIONES", DbType="Text")] string rEGLAB_ANOTACIONES, 
					[Parameter(Name="REGLAB_XML", DbType="Text")] string rEGLAB_XML, 
					[Parameter(Name="SUREFERENCIA", DbType="VarChar(50)")] string sUREFERENCIA, 
					[Parameter(Name="CLIE_ID", DbType="Int")] System.Nullable<int> cLIE_ID, 
					[Parameter(Name="NIVURG_ID", DbType="Int")] System.Nullable<int> nIVURG_ID, 
					[Parameter(Name="REGLAB_HORA", DbType="VarChar(5)")] string rEGLAB_HORA, 
					[Parameter(Name="REGLAB_FECHAMUESTREO", DbType="VarChar(10)")] string rEGLAB_FECHAMUESTREO, 
					[Parameter(Name="REGLAB_HORAMUESTREO", DbType="VarChar(5)")] string rEGLAB_HORAMUESTREO, 
					[Parameter(Name="REGLAB_FECHAMAXIMA", DbType="VarChar(10)")] string rEGLAB_FECHAMAXIMA, 
					[Parameter(Name="REGLAB_HORAMAXIMA", DbType="VarChar(5)")] string rEGLAB_HORAMAXIMA, 
					[Parameter(Name="REGLAB_EMPRESAMUESTREO", DbType="VarChar(1)")] string rEGLAB_EMPRESAMUESTREO, 
					[Parameter(Name="REGLAB_MUESTREADOR", DbType="VarChar(50)")] string rEGLAB_MUESTREADOR, 
					[Parameter(Name="REGLAB_FECHARECOGIDA", DbType="VarChar(10)")] string rEGLAB_FECHARECOGIDA, 
					[Parameter(Name="REGLAB_HORARECOGIDA", DbType="VarChar(5)")] string rEGLAB_HORARECOGIDA, 
					[Parameter(Name="REGLAB_EMPRESARECOGIDA", DbType="VarChar(1)")] string rEGLAB_EMPRESARECOGIDA, 
					[Parameter(Name="REGLAB_RECOGEDOR", DbType="VarChar(50)")] string rEGLAB_RECOGEDOR, 
					[Parameter(Name="REGLAB_PERSONAENTRADA", DbType="Int")] System.Nullable<int> rEGLAB_PERSONAENTRADA, 
					[Parameter(Name="MUESTRA_DESCRIPCION", DbType="VarChar(70)")] string mUESTRA_DESCRIPCION, 
					[Parameter(Name="MUESTRA_REF1", DbType="VarChar(70)")] string mUESTRA_REF1, 
					[Parameter(Name="MUESTRA_REF2", DbType="VarChar(70)")] string mUESTRA_REF2, 
					[Parameter(Name="MUESTRA_REF3", DbType="VarChar(70)")] string mUESTRA_REF3, 
					[Parameter(Name="MUESTRA_OBSERVACIONES", DbType="VarChar(100)")] string mUESTRA_OBSERVACIONES, 
					[Parameter(Name="MUESTREADOR_PERS_ID", DbType="Int")] System.Nullable<int> mUESTREADOR_PERS_ID, 
					[Parameter(Name="RECOGEDOR_PERS_ID", DbType="Int")] System.Nullable<int> rECOGEDOR_PERS_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO, uSUARIO, dOCU_ID, rEGLAB_ID, eSTDOC_ID, rEGLAB_FECHA, dOCU_ID_ORIGEN, dOCU_NUMERO_ORIGEN, aRTI_ID1, rEGLAB_ANOTACIONES, rEGLAB_XML, sUREFERENCIA, cLIE_ID, nIVURG_ID, rEGLAB_HORA, rEGLAB_FECHAMUESTREO, rEGLAB_HORAMUESTREO, rEGLAB_FECHAMAXIMA, rEGLAB_HORAMAXIMA, rEGLAB_EMPRESAMUESTREO, rEGLAB_MUESTREADOR, rEGLAB_FECHARECOGIDA, rEGLAB_HORARECOGIDA, rEGLAB_EMPRESARECOGIDA, rEGLAB_RECOGEDOR, rEGLAB_PERSONAENTRADA, mUESTRA_DESCRIPCION, mUESTRA_REF1, mUESTRA_REF2, mUESTRA_REF3, mUESTRA_OBSERVACIONES, mUESTREADOR_PERS_ID, rECOGEDOR_PERS_ID);
			rEGLAB_ID = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
