#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auxiliares.Alertas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="local")]
	public partial class AlertasClienteDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AlertasClienteDBDataContext() : 
				base(global::Auxiliares.Properties.Settings.Default.localConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AlertasClienteDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlertasClienteDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlertasClienteDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlertasClienteDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.Q2_ALERTAS_CLIENTE")]
		public ISingleResult<Q2_ALERTAS_CLIENTEResult> Q2_ALERTAS_CLIENTE([Parameter(Name="FECHA", DbType="VarChar(10)")] string fECHA, [Parameter(Name="CLIE_ID", DbType="Int")] System.Nullable<int> cLIE_ID, [Parameter(Name="DOCU_ID", DbType="VarChar(6)")] string dOCU_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fECHA, cLIE_ID, dOCU_ID);
			return ((ISingleResult<Q2_ALERTAS_CLIENTEResult>)(result.ReturnValue));
		}
	}
	
	public partial class Q2_ALERTAS_CLIENTEResult
	{
		
		private int _PRMS_ID;
		
		private string _PRMS_FECHAD;
		
		private string _PRMS_FECHAH;
		
		private int _MENS_ID;
		
		private string _PRMS_AMPLIACION;
		
		private string _DOCU_ID;
		
		private string _MENS_MENSAJE;
		
		private string _MENS_DESCRIPCION;
		
		private string _MENS_TIPO;
		
		private string _MENS_SONORO;
		
		public Q2_ALERTAS_CLIENTEResult()
		{
		}
		
		[Column(Storage="_PRMS_ID", DbType="Int NOT NULL")]
		public int PRMS_ID
		{
			get
			{
				return this._PRMS_ID;
			}
			set
			{
				if ((this._PRMS_ID != value))
				{
					this._PRMS_ID = value;
				}
			}
		}
		
		[Column(Storage="_PRMS_FECHAD", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PRMS_FECHAD
		{
			get
			{
				return this._PRMS_FECHAD;
			}
			set
			{
				if ((this._PRMS_FECHAD != value))
				{
					this._PRMS_FECHAD = value;
				}
			}
		}
		
		[Column(Storage="_PRMS_FECHAH", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PRMS_FECHAH
		{
			get
			{
				return this._PRMS_FECHAH;
			}
			set
			{
				if ((this._PRMS_FECHAH != value))
				{
					this._PRMS_FECHAH = value;
				}
			}
		}
		
		[Column(Storage="_MENS_ID", DbType="Int NOT NULL")]
		public int MENS_ID
		{
			get
			{
				return this._MENS_ID;
			}
			set
			{
				if ((this._MENS_ID != value))
				{
					this._MENS_ID = value;
				}
			}
		}
		
		[Column(Storage="_PRMS_AMPLIACION", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PRMS_AMPLIACION
		{
			get
			{
				return this._PRMS_AMPLIACION;
			}
			set
			{
				if ((this._PRMS_AMPLIACION != value))
				{
					this._PRMS_AMPLIACION = value;
				}
			}
		}
		
		[Column(Storage="_DOCU_ID", DbType="VarChar(6)")]
		public string DOCU_ID
		{
			get
			{
				return this._DOCU_ID;
			}
			set
			{
				if ((this._DOCU_ID != value))
				{
					this._DOCU_ID = value;
				}
			}
		}
		
		[Column(Storage="_MENS_MENSAJE", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string MENS_MENSAJE
		{
			get
			{
				return this._MENS_MENSAJE;
			}
			set
			{
				if ((this._MENS_MENSAJE != value))
				{
					this._MENS_MENSAJE = value;
				}
			}
		}
		
		[Column(Storage="_MENS_DESCRIPCION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MENS_DESCRIPCION
		{
			get
			{
				return this._MENS_DESCRIPCION;
			}
			set
			{
				if ((this._MENS_DESCRIPCION != value))
				{
					this._MENS_DESCRIPCION = value;
				}
			}
		}
		
		[Column(Storage="_MENS_TIPO", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MENS_TIPO
		{
			get
			{
				return this._MENS_TIPO;
			}
			set
			{
				if ((this._MENS_TIPO != value))
				{
					this._MENS_TIPO = value;
				}
			}
		}
		
		[Column(Storage="_MENS_SONORO", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MENS_SONORO
		{
			get
			{
				return this._MENS_SONORO;
			}
			set
			{
				if ((this._MENS_SONORO != value))
				{
					this._MENS_SONORO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
